apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-zeppelin
  labels:
    app: {{ template "zeppelin.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "zeppelin.name" . }}
        release: {{ .Release.Name }}
    spec:
      hostNetwork: false
      terminationGracePeriodSeconds: 0
{{- if .Values.spark.useImage }}      
      initContainers:
        - name: spark-home-init 
          image: {{ .Values.spark.image.tag }}
          command: ["sh", "-c", "cp -r {{ .Values.spark.image.path }}/* /spark/"]
          volumeMounts:
          - name: spark-home
            mountPath: /spark
{{- else }}
      initContainers:
        - name: spark-home-init
          image: byrnedo/alpine-curl
          command: ["sh", "-c", "curl {{ .Values.spark.download.link }} >> /spark.tar.gz && 
                     tar -xpvf /spark.tar.gz -C /spark/ --strip-components=1 &&
                     rm -f /spark/python/lib/py4j-* &&
                     curl https://files.pythonhosted.org/packages/ac/26/6aced3634390aa7e49bd30c647a4890095b5d22fae940b4d3fd653368c3d/py4j-0.10.6.zip >> /spark/python/lib/py4j-0.10.6-src.zip"]
          volumeMounts:
          - name: spark-home
            mountPath: /spark
{{- end }}
      containers:
        - name: zeppelin
          image: {{ .Values.zeppelin.image }}
          ports:
            - containerPort: 8080
              name: web
            - containerPort: {{ .Values.spark.driver.port }}
              name: spark-driver
              protocol: TCP
            - containerPort: 30322
              name: spark-blkmgr
              protocol: TCP
          env:
{{ toYaml .Values.spark.env | indent 12 }} 
            - name: ZEPPELIN_PORT
              value: "8080"
            - name: SPARK_HOME
              value: /spark
            - name: SPARK_CONF_DIR
              value: /spark/conf
            - name: HADOOP_CONF_DIR
              value: {{ .Values.hadoop.configPath }}
{{- if .Values.hadoop.useConfigMap }}
            - name: MASTER
              value: "yarn-client"
            - name: SPARK_SUBMIT_OPTIONS
              value: >-
                --deploy-mode client 
                --conf "spark.driver.extraClassPath=/extraJars/spark-jars/*"
                {{ .Values.spark.submit_options }}

{{- end }}
          volumeMounts:
            - name: spark-home
              mountPath: /spark
{{- if .Values.spark.sparkDefaults.enabled }}
            - name: spark-defaults
              mountPath: /spark/conf
{{- end }}              
{{- if .Values.spark.additionalJars.enabled }}
            - name: hadoop-jars
              mountPath: /extraJars
{{- end }}
{{- if .Values.hadoop.useConfigMap }}
            - mountPath: {{ .Values.hadoop.configPath }}
              name: hadoop-config
              defaultMode: 0777
{{- end }}
          resources:
{{ toYaml .Values.zeppelin.resources | indent 12 }} 
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
      volumes:
        - name: spark-home
          emptyDir: {}
{{- if .Values.spark.sparkDefaults.enabled }}
        - name: spark-defaults
          configMap:
            name: {{ .Values.spark.sparkDefaults.configMapName }}
            items:
            - key: spark-defaults.conf
              path: spark-defaults.conf
{{- end }}  
{{- if .Values.spark.additionalJars.enabled }}
        - name: hadoop-jars
          persistentVolumeClaim:
            claimName: {{ .Values.spark.additionalJars.claimName }}
{{- end }}
{{- if .Values.hadoop.useConfigMap }}
        - name: hadoop-config
          configMap:
            name: {{ .Values.hadoop.configMapName }}
            defaultMode: 0777
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
